### ISSUE TITLE
rsync添加密码端口后传输为空

### ISSUE THREAD

**Issue by novvoo** [pigsboss/toolbox#1]
```
python pfetch.py -azu user@server:/path fetch_list ./
```
1.修改pfetch.py里面的rsync 添加密码和端口，传输还是空的， 
2.fetch_list 这个参数需要手动创建吗？ 有时候有上万个文件夹不可能一个个创建

**Comment by pigsboss** [comment]
抱歉，刚刚发现这条消息。估计您早就用其他方式解决了2019年的问题。我当时写这个小玩具的目的就是完成服务器到本地或本地到服务器的百万量级文件同步，所以fetch_list这个文件是用find命令生成的。密码以及端口是放在~/.ssh/config里的。
